//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOEventsWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class EventRegistration
    {
        [IgnoreDataMember]
        public int RegistrationID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public Nullable<int> AdultTickets { get; set; }
        public Nullable<int> ChildTickets { get; set; }
        [IgnoreDataMember]
        public int EventID { get; set; }
        [IgnoreDataMember]
        public virtual Event Event { get; set; }
    }
}
